### ISSUE TITLE
How to disable spamd

### ISSUE THREAD

**Issue by shangdiyisi** [Flolagale/mailin#110]
I found spamd will cost a lot of CPU resource, so i want to disable spamd

**Comment by shangdiyisi** [comment]
Sometimes spamd will raise up CPU's usage rate to 100%

**Comment by Flolagale** [comment]
You can just uninstall it or stop the spamd deamon, mailin won't use it in this case.

**Comment by shangdiyisi** [comment]
But i will get the error message on log. How to close the log

**Comment by shangdiyisi** [comment]
How to close the log  "error: Error: Unable to compute spam score."

**Comment by shangdiyisi** [comment]
I used 'yum remove' command to uninstall spamd, and i no longer receive the error message
