### ISSUE TITLE
ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by samwkg** [Flolagale/mailin#111]
Hello,

I get this error. My Node version is 7.1.0

```
/mailin/node_modules/smtp-server/lib/smtp-server.js:27
    this.secureContext = new Map();
                             ^
ReferenceError: Map is not defined
    at new SMTPServer (../mailin/node_modules/smtp-server/lib/smtp-server.js:27:30)
    at Mailin.start (/node/node_modules/mailin/lib/mailin.js:488:18)
    at /node/mail.js:11:12
    at Object.<anonymous> (/node/mail.js:49:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

**Comment by Flolagale** [comment]
@samwkg this is a native Javascript object. I can't see any reason for it to be undefined. Are you sure for the node version? (`node --version`)

**Comment by samwkg** [comment]
Hello, 

It is v7.1.0

![nodeversion](https://cloud.githubusercontent.com/assets/20674765/20196023/f230f312-a7ec-11e6-826f-087b32b4c190.jpg)


This is running on AWS.

Thanks,
Sam

**Comment by samwkg** [comment]
It shows this weird message as well.

`*****
Your current node version (v0.10.46) is not compatible with Mailin v3.0.3 which requires node ~0.12.4.
If you are running an older version of node, please consider installing Mailin ^2.0.0 (npm install mailin@2.0.0).
Love,
the Mailin maintainers.
*****
`

**Comment by 2franix** [comment]
The message is not weird, it is quite precise: you have to either upgrade your version of node or downgrade your version of mailin.
You are currently attempting to run mailin v3.0.3 which expects at least node v0.12.4.

Resolve this version inconsistency. And if that does not solve the "Map is not defined" issue, please provide more details.

**Comment by samwkg** [comment]
Hi @2franix, 

Thanks for your response. As I mentioned before, my node version is v7.1.0.

Cheers,
Sam

**Comment by samwkg** [comment]
I'm running the sample code in the "Embedded inside a node application" section in the official package page. 

https://www.npmjs.com/package/mailin

**Comment by 2franix** [comment]
Yes, my bad, too fast. But this is quite surprising anyway. 

Can you print process.execPath at runtime to be sure you are executing the program you intended?

**Comment by samwkg** [comment]
@2franix, thanks for your response. Following is my path /usr/bin/node

**Comment by 2franix** [comment]
OK. A few questions, then:

1. what is the output of "which node"
2. what is the output of "/usr/bin/node --version"
3. what is the exact command line you use to start mailin?

1 & 2 are to make sure you do not have two installed versions of node that conflict with each other.

**Comment by samwkg** [comment]
Hi all, 

Thanks for all of your responses. I reinstalled Node and Mailin. It fixed my issue.

Cheers!
Sam
