### ISSUE TITLE
Does mailin stop working?

### ISSUE THREAD

**Issue by donle** [Flolagale/mailin#117]
My code has been used for 3 month, but it stopped working a couple of days ago. And I tried the demo on the home page, the demo account didn't work as well.

**Comment by Flolagale** [comment]
@donle the demo is down due to some dns issues. For your code, I don't see any issue that would stop it working. Did you upgrade your node version or something?

**Comment by donle** [comment]
@Flolagale No, I didn't do any changes. If there is no issue regarding the mail server, then my problem could be solved anyway. Thanks!
