### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by franciscop** [Flolagale/mailin#118]
Steps to reproduce:

1. Open mailin.io
2. Copy the email shown there
3. Create and send a new email. Subject: "Demo", body: "This is a test email".
4. Nothing changes after 10 minutes

Expected: 4. The message is shown on the screen.

Browser: Firefox (latest) on Ubuntu 16.04
The console correctly printed `Object { message: "Subscribed to room iwrhlt" }`

The email I used is `iwrhlt@demo.mailin.io`. Did it never reach your server or did it reach the server but was not displayed properly?

**Comment by 2franix** [comment]
In #117, @Flolagale explained earlier this week that the demo was down due to DNS-related issues. I believe these have not been fixed yet.

**Comment by franciscop** [comment]
Ah sorry, I tried searching specifically for the demo not working but didn't see that issue. I'll leave this open as you might want to keep it open until it's fixed, please close this issue otherwise.

**Comment by ofsahin** [comment]
here is the mailer daemon response  i got with yandex mail:

> This is the mail system at host yandex.ru.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> Please, do not reply to this message.
> 
> 
> <ix9nmf@demo.mailin.io>: connect to mxmailin1.mailin.io[188.226.213.27]:25:
>     Connection refused
