### ISSUE TITLE
Simplesmtp is deprecated!?

### ISSUE THREAD

**Issue by xpepermint** [Flolagale/mailin#23]
From https://github.com/andris9/simplesmtp

```
This module is deprecated for production use. 
For SMTP servers use Haraka, for SMTP clients use smtp-connection.
```

We'll have to move to Haraka?

**Comment by zeroware** [comment]
Or you can take over the simplesmtp project to be compatible with future version of Node.JS ...
Haraka is good but as you said it's a heavy dependency.

**Comment by zeroware** [comment]
Nevermind the author of simplesmtp has created a successor : https://github.com/andris9/smtp-server

**Comment by Flolagale** [comment]
Awesome! Thanks for the news @zeroware.

**Comment by brod** [comment]
sooo, any news on https://github.com/andris9/smtp-server integration?

**Comment by Flolagale** [comment]
Not for the moment, but this is definitely something I'd like to do.

**Comment by DavidTanner** [comment]
PR #44 updates to use smtp-server

**Comment by Flolagale** [comment]
Thanks to @DavidTanner mailin 3.0.0+ now uses [smtp-server](https://github.com/andris9/smtp-server) and runs on node ^0.12.0 and iojs.
