### ISSUE TITLE
ECONNRESET upon receiving message

### ISSUE THREAD

**Issue by crossoft** [Flolagale/mailin#28]
@Flolagale I love the simplicity of mailin ... I hope we can keep it around.  Simplest implementation here - it throws an ECONNRESET when an email is received.  I'm sending it to test-recipient@98.100.60.64 from an Exchange server.  Also tried from GMail.  Same error thrown once the email comes in.  Any suggestions?

var mailin = require('mailin');
mailin.start({ port: 25, disableWebhook: true  });
mailin.on('message', function (connection, data, content) { console.log(data); });

Error: write ECONNRESET
    at errnoException (net.js:904:11)
    at Socket._write (net.js:645:26)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at Socket.Writable.write (_stream_writable.js:182:11)
    at Socket.write (net.js:615:40)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at EncryptedStream.pipeOnReadable (_stream_readable.js:642:5)
    at EncryptedStream.emit (events.js:92:17)

**Comment by jus101** [comment]
I'm getting similar error:

events.js:72
throw er; // Unhandled 'error' event
Error: write ECONNRESET
at errnoException (net.js:904:11)
at Object.afterWrite (net.js:720:19)

Oddly enough - it only seems to happen when sending mail from Office 365 Outlook Web App. Gmail and live.com work fine.

**Comment by Flolagale** [comment]
Right, I remarked that sometimes simplesmtp has this problem with some sending servers. Do you receive the message or does it crashes beforehand?

**Comment by jus101** [comment]
I receive the message (but crashes before the "message" event). Btw, I enabled debug - here's the output - not sure if it helps:

verbose: Parsing email.
OUT: "250 2.0.0 Ok: queued as a2e9c2740fc23e087f49"
COMMAND: 
verbose: Detecting language.
verbose: Potential languages: [ [ 'english', 0.27817777777777786 ],
  [ 'pidgin', 0.1864444444444444 ] ]
COMMAND: QUIT
OUT: "221 2.0.0 Goodbye!"
OUT: "421 4.4.2 54ad9eb4f43e Error: client error"

events.js:72
throw er; // Unhandled 'error' event
Error: write ECONNRESET
at errnoException (net.js:904:11)
at Object.afterWrite (net.js:720:19)

**Comment by jus101** [comment]
CONNECTION FROM x.x.x.x
Connection from x.x.x.x
OUT: "220 54ad9eb4f43e ESMTP smtp"
COMMAND: EHLO APAC01-SG1-obe.outbound.protection.outlook.com
OUT: "250-54ad9eb4f43e at your service, [x.x.x.x]
250-8BITMIME
250-ENHANCEDSTATUSCODES
250 STARTTLS"
COMMAND: STARTTLS
OUT: "220 2.0.0 Ready to start TLS"
WARNING: TLS ERROR (Error: UNABLE_TO_GET_ISSUER_CERT)
TLS CONNECTION STARTED
COMMAND: EHLO APAC01-SG1-obe.outbound.protection.outlook.com
OUT: "250-54ad9eb4f43e at your service, [x.x.x.x]
250-8BITMIME
250 ENHANCEDSTATUSCODES"
COMMAND: MAIL FROM:<x>
OUT: "250 2.1.0 Ok"
COMMAND: RCPT TO:<x>
OUT: "250 2.1.0 Ok"
COMMAND: DATA
OUT: "354 End data with <CR><LF>.<CR><LF>"
info: Receiving message from x
verbose: Connection id 3c4c01e5

**Comment by jus101** [comment]
Looks like a node 0.10 / simplesmtp issue:
https://github.com/andris9/simplesmtp/issues/25

**Comment by Flolagale** [comment]
@crossoft @jus101 should be fixed in mailin 3.0.0+, we moved to [smtp-server](https://github.com/andris9/smtp-server).
