### ISSUE TITLE
Receive notifications

### ISSUE THREAD

**Issue by bl0zis** [Flolagale/mailin#34]
Is there a way to connect a smartphone to server and receive inbox notifications?

Like notifications of gmail...

**Comment by Flolagale** [comment]
The fastest way to get a prototype working, in my opinion, would be to get a [pushover.net](https://pushover.net) account and to integrate mailin in a script that crafts a suitable payload for their [API](https://pushover.net/api#messages).

**Comment by Flolagale** [comment]
If that is ok with you @bl0zis, I close this issue. Feel free to reopen.
