### ISSUE TITLE
Better documentation - smtpOptions

### ISSUE THREAD

**Issue by tkambler** [Flolagale/mailin#36]
I spent about an hour trying to figure out why I could not get my Jenkins CI/CD server to work with mailin. I finally realized that I needed to pass this in:

```
'smtpOptions': {
    'disableDNSValidation': true
}
```

I realize this option is for a separate library used by mailin, but it seems like mailin's documentation could at least point out the fact that if they run into issues, they may need to investigate `simplesmtp`.

**Comment by tkambler** [comment]
Better yet... given what I think is the primary audience of this lib, I'd recommend making this the default.

**Comment by Flolagale** [comment]
Good remark, I'll change that. Sorry for making you dive into simplesmtp ;-).

**Comment by tkambler** [comment]
Np. Thanks for this - really useful!

**Comment by Flolagale** [comment]
@tkambler Sender/recipient domain validation via DNS is now disabled by default. The new version is published on npm.

**Comment by tkambler** [comment]
Awesome - thx! :+1:
