### ISSUE TITLE
Empty payload (req.body) received by my app

### ISSUE THREAD

**Issue by colingoldberg** [Flolagale/mailin#40]
Hi,

Starting mailin as root, it says it successfully posted an incoming email to my webhook.

But my (nodejs) app gets an empty request body.

mailin displays:
info: Receiving message from <my email address>
info: Processing message from <my email address>
info: Sending request to webhook http://localhost:3000/run/emailin
info: Convert attachments to strings 
{ duration: '0ms' }
info: Succesfully posted to webhook http://localhost:3000/run/emailin
info: End processing message.

Is there a logging/debug option that I can use to see what is happening?

Colin G

**Comment by Flolagale** [comment]
You can use the `--verbose` and `--debug` options with the mailin command line to activate debug printouts. Issue `mailin -h` for a full list of options. You can also try to create a [postbin](http://requestb.in/) and use the url as a webhook to see if you get a payload there.
Please keep me updated if you find a solution!

**Comment by colingoldberg** [comment]
I had not implemented parsing properly - using multiparty. So once that was done it worked like a charm.

Thanks for your help.

Colin G

**Comment by Flolagale** [comment]
Awesome! Glad to have helped you.
