### ISSUE TITLE
Where are message attachments?

### ISSUE THREAD

**Issue by junajan** [Flolagale/mailin#41]
Hello,
I was trying to send email with pdf file but in mailin message event handler I get only these fields in attachments attribute of data variable:

```javascript
 [ { contentType: 'application/pdf',
       contentDisposition: 'attachment',
       fileName: 'request.pdf',
       generatedFileName: 'request.pdf',
       contentId: '9d35d04b15f736a56b8ea607ea69fae4@mailparser' } ],
```

In examples there is always some content field with file data.. Am I missing something? How can I retrieve data of sent PDF? Can you help me please?

**Comment by junajan** [comment]
Ahh, my bad.. - There was problem in nodemailer with handling PDF file content..

**Comment by rogerthealien** [comment]
Hi,

I'm having the same problem with sending 'png' attachments. Could you maybe post the solution you found? 

Thanks!

**Comment by junajan** [comment]
Hi @rogerthealien - the problem was when sending an email with nodemailer - I put there something wrong (I think that it was wrong path to file) so it did not send file content..
