### ISSUE TITLE
ENOENT when processing incoming message

### ISSUE THREAD

**Issue by gmdayley** [Flolagale/mailin#42]
I randomly get the following error when running.  It doesn't happen on every message.

verbose: Validating spf.
verbose: Parsing email.
OUT: "250 2.0.0 Ok: queued as 6bb731f4038f12a8e7c6"
COMMAND:
{ [Error: ENOENT, open '.tmp/5536ed281ced6be3342688908dc292b707e70746']
  errno: 34,
  code: 'ENOENT',
  path: '.tmp/5536ed281ced6be3342688908dc292b707e70746' }
We got an error when trying to read the file!!!
error: Error: ENOENT, open '.tmp/5536ed281ced6be3342688908dc292b707e70746'

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '.tmp/5536ed281ced6be3342688908dc292b707e70746'
info: Mailin stopped.

**Comment by DavidTanner** [comment]
The issue is that the connection variable is not always unique.  After adding more logging I could see where the file is being unlinked after the previous message completes.  PR forthcoming
