### ISSUE TITLE
Mailin not using my options and AUTH LOGIN command not working

### ISSUE THREAD

**Issue by HanrichPotgieter** [Flolagale/mailin#45]
Hi guys Mailin is not applying my options to the server. Also the events are not emitted after a connection is established with the smtp server. 

![screen shot 2015-07-26 at 9 12 59 am](https://cloud.githubusercontent.com/assets/8564706/8892918/88ebcb0c-3376-11e5-9061-85b29771e5b4.png)

![screen shot 2015-07-26 at 9 14 51 am](https://cloud.githubusercontent.com/assets/8564706/8892927/d2f6e20e-3376-11e5-95d2-025202ed9c55.png)

I am struggling to get the server working with a small hunting camera that needs to send emails to the server.

**Comment by HanrichPotgieter** [comment]
I have done some extra research regarding my problem. I used haraka to log the connection from the camera and it fails because mailin does not use the AUTH LOGIN command. I tried turning authorization on in mailin.  Should I be able to use AUTH LOGIN when logging into mailin with telnet?

**Comment by DavidTanner** [comment]
You can enable the auth stage by giving an empty list to the disable commands parameter ```--disabled-smtp-commands ''```
