### ISSUE TITLE
Update version requirements?

### ISSUE THREAD

**Issue by mariusk** [Flolagale/mailin#53]
The docs says iojs 2.0 is required, but it seems to work fine with 3.2 as well, despite the warnings. Granted, I've only done some basic testing. But unless there are specific reasons why it shouldn't work with newer versions, maybe the warnings should be removed. Alternatively, how about saying WHY the specific version is required so people can fix it or have an idea of when it should be working with more modern versions?

**Comment by Flolagale** [comment]
Sure, iojs 3+ will work fine, there should not be any warnings ! That is a bug. These warnings were designed to prevent using node 0.10 or older.

**Comment by t3chguy** [comment]
Also more recently Node 4.x.x

**Comment by Kagammor** [comment]
Node.js and io.js merged months ago and Node 5.x.x has been released, which Mailin thinks is a version older than v0.12.4. Can this check please be removed or updated? Thanks!

**Comment by Flolagale** [comment]
All, a new mailin version is published, the check has been updated thans to @tomforster.
