### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by SiddiqueAhmad** [Flolagale/mailin#55]
could not find this versino,

**Comment by 2franix** [comment]
Have you seen https://github.com/Flolagale/mailin/releases/tag/v2.0.0 ?
Looks like this is what you are looking for.

**Comment by SiddiqueAhmad** [comment]
true, but was saying for npm

**Comment by 2franix** [comment]
Your first message was not clear about that.
I cannot find the version 2.0.0 on npm either.

**Comment by SiddiqueAhmad** [comment]
sorry i could not write it fully, 
yes, let me re phrase it, 

npm install mailin@2.0.0 is not installing

**Comment by 2franix** [comment]
No worries, I got your meaning on your previous message :) I confirmed I cannot find the version 2.0.0 on npm either. I think only @Flolagale can tell you why.

In the interim, you can still use the version 2.0.0 by installing it manually from the source tarball. Not that convenient but it is a workaround.

**Comment by SiddiqueAhmad** [comment]
i did, can you guide me, do we need to listen ports of smtp for this to work ??

**Comment by Flolagale** [comment]
I just double checked, there is a mistake in package.json, what is tagged as Version 2.0.0 is actually 1.0.1.
@SiddiqueAhmad Which node version are you running?

**Comment by SiddiqueAhmad** [comment]
0.10

**Comment by Flolagale** [comment]
Try `npm install mailin@1.0.1`

**Comment by SiddiqueAhmad** [comment]
i installed it, is there any guide how can i setup 25 port for mailin,

**Comment by Flolagale** [comment]
Have a look at the the [README](https://github.com/Flolagale/mailin/blob/master/README.md) file, it is pretty detailed.
