### ISSUE TITLE
Node v4.1.0

### ISSUE THREAD

**Issue by Martindelataille** [Flolagale/mailin#63]
Hi,

Is it possible to upgrade to Node v4.1.0 ?
I am receiving:
```
Your current node version (v4.1.0) is not compatible with Mailin v3.0.1 which requires node ~0.12.4.
If you are running an older version of node, please consider installing Mailin ^2.0.0 (npm install mailin@2.0.0)
```

Thanks

**Comment by Flolagale** [comment]
Actually, Mailin is compatible with node 4. I put this message to prevent using node 0.10 and the test to trigger the message is bugged, it should not display the message in your case ;-).

**Comment by Martindelataille** [comment]
Ok. Great !

Thanks
