### ISSUE TITLE
Having difficulty using parsed results

### ISSUE THREAD

**Issue by nmai** [Flolagale/mailin#65]
For the life of me I cannot figure out how to grab a simple field like the sender's name or the plaintext body from the parsed results. Can anyone show me a quick example? 

I'll put up some examples of what I've tried tomorrow but I thought I'd ask this before I crash..

**Comment by hebrew878** [comment]
For php i use this

$json=$_POST['mailinMsg];
$mail=json_decode($json);
$text=$mail->text;
$sender_addr=$mail->from[0]->address;

**Comment by nmai** [comment]
Thanks @hebrew878. Turns out my problem was due to the `node-multiparty` parser returning an object wrapped in an array, rather than just the object. So if I tried to grab `mail.text`, I would get undefined.
