### ISSUE TITLE
Attachments are not being parsed

### ISSUE THREAD

**Issue by jkrenge** [Flolagale/mailin#70]
Hi there! First off: I am amazed by mailin, awesome piece of software. Saved me days in development. I have a slight issue with the attachments though:

-----

I am not using the `webhook`, but rather the embedded mailin server. For that, I plugged myself into `mailin.on('message', function(connection, data, content) {});`. And this works fine, but somehow `data.attachments` is always non-existing. For debugging I printed both `data` and `content`:

Excerpt from `content`:

    --Apple-Mail=_1CE57DD1-5830-4E39-BB06-17F285909745
    Content-Disposition: attachment; filename=X
    Content-Type: application/octet-stream;name="X"
    Content-Transfer-Encoding: 7bit

    TEST

But in `data` (shortened):

      { html: 'html',
        headers:
         { received: [ Object object ],
           from: 'Julian Krenge <julian@parcellab.com>',
           to: 'Tracking Agent <track@parcellab.com>',
           subject: 'test',
           'thread-topic': 'test',
           'thread-index': 'AQHRJ1UYzntn5mE26ECrsi6sDecCjw==',
           date: 'Wed, 25 Nov 2015 07:44:20 +0000',
           'message-id': '<06C9DE21-CC9A-4732-AFD6-D48ACC49A74E@parcellab.com>',
           'accept-language': 'de-DE, en-US',
           'content-language': 'en-US',
           'x-ms-has-attach': 'yes',
           'x-ms-tnef-correlator': '',
           'authentication-results': 'spf=none (sender IP is ) smtp.mailfrom=julian@parcellab.com;',
           'x-ms-exchange-messagesentrepresentingtype': '1',
           'x-originating-ip': '[77.47.69.145]',
           'x-microsoft-exchange-diagnostics': 'string,
           'x-microsoft-antispam': 'UriScan:;BCL:0;PCL:0;RULEID:;SRVR:AMXPR07MB184;',
           'x-ld-processed': 'c9ad2ae3-2857-429e-bddf-50e548a323c0,ExtAddr',
           'x-microsoft-antispam-prvs': '<AMXPR07MB184102A08E5ECE495676F2CC6050@AMXPR07MB184.eurprd07.prod.outlook.com>',
           'x-exchange-antispam-report-test': 'UriScan:;',
           'x-exchange-antispam-report-cfa-test': 'BCL:0;PCL:0;RULEID:(601004)(2401047)(5005006)(8121501046)(520078)(10201501046)(3002001);SRVR:AMXPR07MB184;BCL:0;PCL:0;RULEID:;SRVR:AMXPR07MB184;',
           'x-forefront-prvs': '0771670921',
           'x-forefront-antispam-report': 'string',
           'received-spf': 'None (protection.outlook.com: parcellab.com does not designate permitted sender hosts)',
           spamdiagnosticoutput: '1:23',
           spamdiagnosticmetadata: 'NSPM',
           'content-type': 'multipart/signed; boundary="Apple-Mail=_F0CC39CA-E1ED-482A-B618-7EFEA7071FED"; protocol="application/pkcs7-signature"; micalg=sha1',
           'mime-version': '1.0',
           'x-originatororg': 'parcellab.com',
           'x-ms-exchange-crosstenant-originalarrivaltime': '25 Nov 2015 07:44:20.6059 (UTC)',
           'x-ms-exchange-crosstenant-fromentityheader': 'Hosted',
           'x-ms-exchange-crosstenant-id': 'c9ad2ae3-2857-429e-bddf-50e548a323c0',
           'x-ms-exchange-transport-crosstenantheadersstamped': 'AMXPR07MB184' },
        subject: 'test',
        messageId: '06C9DE21-CC9A-4732-AFD6-D48ACC49A74E@parcellab.com',
        priority: 'normal',
        from: [ Array ],
        to: [ Array ],
        date: Wed Nov 25 2015 07:44:20 GMT+0000 (UTC),
        receivedDate: Wed Nov 25 2015 07:44:21 GMT+0000 (UTC),
        dkim: 'failed',
        spf: 'failed',
        spamScore: 0,
        language: 'romanian',
        cc: [],
        connection: [ Object object ],
        envelopeFrom: { address: 'julian@parcellab.com', args: false },
        envelopeTo: [ { address: 'track@track.parcellab.com', args: false } ] }

--------

Then I tried to check the webhook: But enabling this even throws an exception and mailin crashes.

Any ideas? :-)

**Comment by rogerthealien** [comment]
Any updates on this?

**Comment by jkrenge** [comment]
I think I'm just stupid. :-)

**Comment by rogerthealien** [comment]
What happened? I'm having a similar issue: the attachment array is populated correctly, but I have no way to access the actual content of the attachment. I tracked it down to https://github.com/andris9/mailparser#attachment-streaming, and it's pretty clear how to get the actual content from a MailParser instance, but I just don't know how to access that instance from within mailin. Any ideas?

**Comment by jkrenge** [comment]
For me, the whole attribute `attachments` was gone, so I think it was rather removed by different code before processing. But, I hacked it a little bit:

I basically store the whole raw email, as I want to archive the file anyways:

```javascript
mailin.on('message', function(connection, data, content) {
  fs.writeFile(output, content, function(err) {
    if (err) console.log(err);
  });
});
```

Then I monitor the folder where the emails are stored and extract contents manually:

[AttachmentMaster / index.js](https://bitbucket.org/parcellab/attachmentmaster/src/8da449707b398dd2646d54399f0bb33c5d3c1b73/index.js?at=master&fileviewer=file-view-default).

We will fix this, but for the meantime this also kind of works. :-)

**Comment by rogerthealien** [comment]
Thanks! :+1:
