### ISSUE TITLE
Error message "Webhook seems invalid or down" despite accessible URL

### ISSUE THREAD

**Issue by mefernandez** [Flolagale/mailin#72]
Hi there!

I'm using mailin version 3.0.1 from command line, like this:

```
mailin --webhook http://localhost:3000/emails
```

When it starts up, a warning is shown:
```
warn: Webhook http://localhost:3000/emails seems invalid or down. You may want to double check the webhook url.
```

I've curled that URL from the machine mailin is running, and it seems ok.
```
curl -X HEAD -I http://localhost:3000/emails

HTTP/1.1 200 OK
X-Powered-By: Express
Date: Tue, 15 Dec 2015 11:08:39 GMT
Connection: keep-alive
```
So, I started mailin with node-debug and set a breakpoint at [this line of code](https://github.com/Flolagale/mailin/blob/9ffad4388fde31fd595d9579b8b2125704f5fcb9/lib/mailin.js#L112):
```
node-debug /usr/lib/node_modules/mailin/cli.js --webhook http://localhost:3000/emails --port 2500
```

I've found this:
```
/* Check the webhook validity. */
    if (!configuration.disableWebhook) {
        request.head({
            url: configuration.webhook,
            timeout: 3000
        }, function (err, resp) {
            if (err || resp.statusCode !== 200) {
                logger.warn('Webhook ' + configuration.webhook +
                    ' seems invalid or down. You may want to double check the webhook url.');
            } else {
                logger.info('Webhook ' + configuration.webhook + ' is valid, up and running.');
            }
        });
    }
```

In spite of `configuration.webhook` being Ok, `function` is called with this `err`:

![image](https://cloud.githubusercontent.com/assets/845346/11809467/6a7a2436-a327-11e5-9215-11e55c292dcd.png)

It looks like `superagent` is calling `127.0.0.1:80` instead of what's in `configuration.webhook`. S

I've taken a look at [current superagent docs](http://visionmedia.github.io/superagent/#request-basics), and it seems requests are done somewhat differently.

```javascript
request
  .head('/favicon.ico')
  .end(function(err, res){

  });
```
Maybe there's been a change in `superagent` API.

Shall I fork+pull request?

**Comment by Flolagale** [comment]
@mefernandez Nice find. Yes, please submit a PR!

**Comment by RashadSaleh** [comment]
I am still getting this error and I installed mailin today.
