### ISSUE TITLE
What's the difference between fileName and generatedFileName?

### ISSUE THREAD

**Issue by PanMan** [Flolagale/mailin#87]
Why does the sample use Generated filename? 
https://github.com/Flolagale/mailin/blob/d94d017c713d8640f24ff1d6f198b72dd459b433/samples/server.js#L60

Not much wrong with it, but in our testing fileName and generatedFileName usually (always?) are the same. Thanks!

**Comment by Flolagale** [comment]
The generatedFileName is unique. It is built as the concatenation of a random hash + the filename. It allows the mail sender to attach several files with the same name. Remember the last time you attached multiple pictures from your phone ? Most of the time, all the files are named "PHOTO.JPG". ;-)

**Comment by PanMan** [comment]
Awesome, clear. Although I usually don't see content hashes in the filenames. Maybe only when I attach multiple files with the same name?

**Comment by Flolagale** [comment]
I must admit that I don't remember the exact algorithm, but it should be something like this !
