### ISSUE TITLE
Getting "Error: EACCES: permission denied, mkdir '.tmp'

### ISSUE THREAD

**Issue by Roaders** [Flolagale/mailin#96]
I have asked a question about this on SO:

http://stackoverflow.com/q/36435434/151770

but I have not got any answers so I thought I would try here. When mailin find on my Pi it tries to create a .tmp folder but it doesn't have permission.

How do I give node or mailin permission to create directories?

Thanks

**Comment by 2franix** [comment]
I believe you only have to grant write permission to the user that runs mailin. See the chmod and chown utilities.

**Comment by Flolagale** [comment]
@2franix thanks mate

**Comment by Roaders** [comment]
this was solved by passing a different directory in the config for tmp. Setting it to os.tmpdir() did the trick.

**Comment by Flolagale** [comment]
Perfect thanks @Roaders.
