### ISSUE TITLE
Do not receive POST request in user domain sent from webhook post method

### ISSUE THREAD

**Issue by philb89** [Flolagale/mailin#97]
Hi all,

I've setup 2 node servers application. The 1st is mailin server, receive email and send to 2nd server (http://localhost:3000/mailin/incomming).
The code in 1st server:
'use strict';

var mailin = require('mailin');

exports.start = function() {
   
    mailin.start({
        port: 25,
        disableWebhook: false, // Disable the webhook posting.
        webhook: 'http://localhost:3000/mailin/incoming'
    });

    mailin.on('startMessage', function (connection) {
        console.log(connection);
    });

    mailin.on('message', function (connection, data, content) {
        console.log(data);
        require('../test/MailinService').closeConnection().then(function successFunc(){
            logger.info("Close connection");
            process.exit();
        });
     });
};

************* I write a test to send email: ******************

client = new SMTPConnection({
        port: 25,
        ignoreTLS: true,
        host: "localhost"
    });

client.connect(function () {
        logger.info("connect success, sent now");
        client.send({
            from: {
                name: '',
                address: 'From@gmail.com'
            },
            to: [{
                name: '',
                address: 'To@gmail.com'
            }]
        }, fs.createReadStream(path.join(__dirname, 'test.eml')),function (err) {
                if (err) {
                    logger.error(err);
                }
        });
    });

************************************************************************
And the log console when run this:

2016-04-09T16:57:41+07:00 - info PID-19309 Configuration loaded, starting mailin server.
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
2016-04-09T16:57:41+07:00 - info PID-19309 Open connection success
2016-04-09T16:57:41+07:00 - info PID-19309 Connect and send mail
info: Mailin Smtp server listening on port 25
2016-04-09T16:57:42+07:00 - info PID-19309 connect success, sent now
info: 8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a Receiving message from From@gmail.com
{ id: '8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a',
  remoteAddress: '127.0.0.1',
  clientHostname: '[127.0.0.1]',
  hostNameAppearsAs: 'lebaphis-macbook-pro.local',
  xClient: {},
  xForward: {},
  envelope: 
   { mailFrom: { address: 'From@gmail.com', args: false },
     rcptTo: [ [Object] ] },
  transaction: 1,
  mailPath: '.tmp/8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a' }
info: 8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a Processing message from From@gmail.com
2016-04-09T16:57:42+07:00 - info PID-19309 Send mail success
{ html: '<b>Hello world!</b>',
  text: 'Hello world!',
  headers: 
   { 'x-mailer': 'Nodemailer 1.0',
     from: '"Me" <me@gmail.com>',
     to: '"First Receiver" <first@gmail.com>, second@gmail.com',
     'content-type': 'multipart/mixed; boundary="----mailcomposer-?=_1-1402581589619"',
     'mime-version': '1.0' },
  priority: 'normal',
  from: [ { address: 'me@gmail.com', name: 'Me' } ],
  to: 
   [ { address: 'first@gmail.com', name: 'First Receiver' },
     { address: 'second@gmail.com', name: '' } ],
  attachments: 
   [ { contentType: 'text/plain',
       fileName: 'dummyFile.txt',
       contentDisposition: 'attachment',
       transferEncoding: 'base64',
       generatedFileName: 'dummyFile.txt',
       contentId: '6e4a9c577e603de61e554abab84f6297@mailparser',
       checksum: 'e9fa6319356c536b962650eda9399a44',
       length: 28,
       content: <Buffer 6d 79 20 64 75 6d 6d 79 20 61 74 74 61 63 68 6d 65 6e 74 20 63 6f 6e 74 65 6e 74 73> } ],
  dkim: 'failed',
  spf: 'failed',
  spamScore: 0,
  language: 'pidgin',
  cc: [],
  connection: 
   { id: '8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a',
     remoteAddress: '127.0.0.1',
     clientHostname: '[127.0.0.1]',
     hostNameAppearsAs: 'lebaphis-macbook-pro.local',
     xClient: {},
     xForward: {},
     envelope: { mailFrom: [Object], rcptTo: [Object] },
     transaction: 1,
     mailPath: '.tmp/8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a' },
  envelopeFrom: { address: 'From@gmail.com', args: false },
  envelopeTo: [ { address: 'To@gmail.com', args: false } ] }
info: 8a662cf1-0eb4-414d-bbe7-8b4b5d07c14a Sending request to webhook http://localhost:3000/mailin/incoming
info: Convert attachments to strings 
{ durationMs: 0 }
2016-04-09T16:57:42+07:00 - info PID-19309 Close connection

- In 2nd server, code to receive request in 1st is:

.......
appRouter.post('/mailin/incoming', cache, controllers.IntegrationController.receiveMailin);
appRouter.head('/mailin/incoming', function (req, res) {
        logger.log('Received head request from webhook.');
        res.send(200);
    });
.......

But it just hit the method HEAD and DOES NOT hit the method POST...Does anyone got problem like me or plz give me some ideal?

Thanks

**Comment by Flolagale** [comment]
Try to create a request bin [http://requestb.in/](http://requestb.in/) and to use this url as you webhook url, just to see if the mailin webhook hits your request bin.
